name: Integration tests

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test-saucelabs:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Read node version from .nvmrc
        id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

      - name: "Setup Node v${{ steps.nvm.outputs.NVMRC }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: "Run integration tests"
        run: npm run wdio:test
        env:
          SAUCE_ENABLED: "false"  # ensure we don't use Sauce Labs
